web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./code:/var/www/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  image: php:7-fpm
  volumes: 
    - ./code:/var/www/html

phpunit:
  image: php:7.4-cli
  volumes:
    - .:/app
  working_dir: /app
  entrypoint: vendor/bin/phpunit